### ISSUE TITLE
Can you help me    InternalOpenIDError: Failed to discover OP endpoint URL

### ISSUE THREAD

**Issue by UtopiaLogin** [fedebabrauskas/mern-steam-jwt-login#5]
After pulling the project, I tried to run the project locally, but I encountered this error. I don’t know how to deal with it. Can you help me? I pulled passprot-steam before and encountered this problem, but I still didn’t figure it out

InternalOpenIDError: Failed to discover OP endpoint URL
    at E:\Desktop\mern-steam-jwt-login\api\node_modules\_@passport-next_passport-openid@1.0.0@@passport-next\passport-openid\lib\passport-openid\strategy.js:249:52
    at E:\Desktop\mern-steam-jwt-login\api\node_modules\_openid@2.0.6@openid\openid.js:788:14
    at E:\Desktop\mern-steam-jwt-login\api\node_modules\_openid@2.0.6@openid\openid.js:578:13
    at E:\Desktop\mern-steam-jwt-login\api\node_modules\_openid@2.0.6@openid\openid.js:534:11
    at Request._callback (E:\Desktop\mern-steam-jwt-login\api\node_modules\_openid@2.0.6@openid\openid.js:227:7)
    at self.callback (E:\Desktop\mern-steam-jwt-login\api\node_modules\_request@2.88.2@request\request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.onRequestError (E:\Desktop\mern-steam-jwt-login\api\node_modules\_request@2.88.2@request\request.js:877:8)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by UtopiaLogin** [comment]
![clent](https://user-images.githubusercontent.com/50434151/87875606-fe19b900-ca04-11ea-9240-caba958697af.png)
![Uploading api.png…]()
